name: Exceptunity
version: 0.0.0-00
main: net.exceptionmc.Exceptunity

depend:
  - Framework
  - WorldEdit
  - WorldGuard
  - WGRegionEvents

commands:
  set:
    description: set
  spawn:
    description: spawn
